name: CI

on: [push, pull_request, merge_group]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version-file: ".tool-versions"
          cache: "npm"
      - run: npm ci
      - run: npm test
  orphan-job:
    runs-on: ubuntu-latest
    steps:
      - name: Orphan step 1
        run: echo "Hello world!"
